spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: puja@123
    url: jdbc:mysql://localhost:3306/sbms36
    username: root
  jpa:
   show-sql: true
    
   hibernet:
     ddl-auto: update
     
     
server:
 port: 8081
        