server:
  port: 3333

spring:
  cloud:
    gateway:
      routes:
      - id: welcome-api
        uri: lb://Welcome-API
        predicates:
        - Path=/welcome
      - id: greet-api
        uri: lb://Greet-API
        predicates:
        - Path=/greet
        
        application:
          name:Cloud_Api_Ga teway